In [1]:
print(f"Using Jupyter Kernel: kernel_python_tricks to create a Jupyter notebook")

Using Jupyter Kernel: kernel_python_tricks to create a Jupyter notebook


In [2]:
import numpy as np

In [3]:
vb = np.array([
    [9,8,7],
    [6,5,4],
    [1,2,3],
])

In [4]:
vb

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [7]:
print(f"{vb}")

[[9 8 7]
 [6 5 4]
 [1 2 3]]
